<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id(katalon-spy_elementInfoDiv)</name>
   <tag></tag>
   <elementGuidId>1fc0e649-ade2-4d0d-b0fb-aa419f1bbc13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon-spy_elementInfoDiv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#katalon-spy_elementInfoDiv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7fc3ae64-862d-4aad-bfaf-7c8f0bf8c1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-spy_elementInfoDiv</value>
      <webElementGuid>50e020c9-1213-46de-b593-7fd4ab7b3162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;katalon-spy_elementInfoDiv&quot;)</value>
      <webElementGuid>8b9b716d-9457-48b0-b711-7f8466f647f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-spy_elementInfoDiv&quot;)</value>
      <webElementGuid>70f4b4d0-40e9-477d-ab8f-7014e667f9a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='katalon-spy_elementInfoDiv']</value>
      <webElementGuid>501c3024-3366-459a-b76b-38e2cffc471e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon']/div[2]</value>
      <webElementGuid>8ce31e84-1bd8-4686-a59f-ce8f4f273197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[1]</value>
      <webElementGuid>57cdcea8-9e44-4012-8531-aaf06aa05c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[1]</value>
      <webElementGuid>6986b94c-d403-4c57-b0a1-27994a7fb25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='id(&quot;katalon-spy_elementInfoDiv&quot;)']/parent::*</value>
      <webElementGuid>f91aac07-6531-4c04-90c4-17a80a9c509c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>43fdee12-164a-46a1-a985-4d808f8fe859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'katalon-spy_elementInfoDiv' and (text() = 'id(&quot;katalon-spy_elementInfoDiv&quot;)' or . = 'id(&quot;katalon-spy_elementInfoDiv&quot;)')]</value>
      <webElementGuid>61ad13b9-9056-46e9-897c-261b2e3f05a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
